# Fastfetch personal para Arch
show_os="on"
show_host="on"
show_kernel="on"
show_uptime="on"
show_packages="on"
show_cpu="on"
show_gpu="on"
show_ram="on"
show_disk="on"
show_battery="on"
show_music="on"

# CPU
cpu_brand="on"
cpu_cores="logical"
cpu_speed="on"
cpu_temp="off"

# RAM
memory_percent="on"
memory_unit="mib"

# Disco
disk_show=('/')
disk_percent="on"

# Música
music_player="playerctl"
song_format="%artist% - %title%"
song_shorthand="off"

# Colores y estilo
colors=(distro)
bold="on"
underline_enabled="on"
ascii_distro="Arch"
ascii_colors=(distro)
ascii_bold="on"
