# Fuente
font_family JetBrainsMono Nerd Font 
font_size        11

# Cursor
cursor_shape     block
cursor_blink_interval 0

Ejemplo básico:

# Ventana
background_opacity 0.70
remember_window_size  yes
initial_window_width  900
initial_window_height 600

# Colores (oscuro, legible)
foreground #ffffff
background #000000

selection_foreground #000000
selection_background #ffffff

cursor #ffffff

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

copy_on_select yes

term xterm-kitty
map ctrl+shift+enter new_window
