"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](black)\
$os\
$username\
[](bg:gray2 fg:black)\
$directory\
[](bg:gray3 fg:gray2)\
$git_branch\
$git_status\
[](fg:gray3 bg:gray4)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:gray4 bg:gray5)\
$conda\
[](fg:gray5 bg:white)\
$time\
[ ](fg:white)\
$cmd_duration\
$line_break\
$character"""

palette = "grayscale"

[os]
disabled = false
style = "bg:black fg:white"

[os.symbols]
Arch = "󰣇"
Linux = "󰌽"

[username]
show_always = true
style_user = "bg:black fg:white"
style_root = "bg:black fg:white"
format = '[ $user]($style)'

[directory]
style = "bg:gray2 fg:white"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:gray3"
format = '[[ $symbol $branch ](fg:white bg:gray3)]($style)'

[git_status]
style = "bg:gray3"
format = '[[($all_status$ahead_behind )](fg:white bg:gray3)]($style)'

[nodejs]
symbol = ""
style = "bg:gray4"
format = '[[ $symbol( $version) ](fg:white bg:gray4)]($style)'

[c]
symbol = " "
style = "bg:gray4"
format = '[[ $symbol( $version) ](fg:white bg:gray4)]($style)'

[rust]
symbol = ""
style = "bg:gray4"
format = '[[ $symbol( $version) ](fg:white bg:gray4)]($style)'

[golang]
symbol = ""
style = "bg:gray4"
format = '[[ $symbol( $version) ](fg:white bg:gray4)]($style)'

[php]
symbol = ""
style = "bg:gray4"
format = '[[ $symbol( $version) ](fg:white bg:gray4)]($style)'

[java]
symbol = " "
style = "bg:gray4"
format = '[[ $symbol( $version) ](fg:white bg:gray4)]($style)'

[kotlin]
symbol = ""
style = "bg:gray4"
format = '[[ $symbol( $version) ](fg:white bg:gray4)]($style)'

[haskell]
symbol = ""
style = "bg:gray4"
format = '[[ $symbol( $version) ](fg:white bg:gray4)]($style)'

[python]
symbol = ""
style = "bg:gray4"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:white bg:gray4)]($style)'

[conda]
symbol = "  "
style = "fg:white bg:gray5"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:white"
format = '[[  $time ](fg:black bg:white)]($style)'

[line_break]
disabled = true

[character]
success_symbol = '[❯](bold fg:white)'
error_symbol = '[❯](bold fg:white)'

[cmd_duration]
show_milliseconds = true
format = "⏱ $duration "
style = "fg:white"
disabled = false


[palettes.grayscale]
black = "#111111"
gray2 = "#2a2a2a"
gray3 = "#3a3a3a"
gray4 = "#555555"
gray5 = "#777777"
white = "#eeeeee"